import { useMemo, useState } from 'react';
import {
  ArrowDownAZ, ArrowUpAZ, BarChart3, Building2, ChevronDown, CircleUserRound,
  ClipboardList, KeyRound, LayoutDashboard, LogOut, Menu, Plus, Search, ShieldCheck,
  Star, Store, UserRound, Users, X
} from 'lucide-react';

type Role = 'admin' | 'user' | 'owner';
type View = 'overview' | 'stores' | 'users' | 'ratings' | 'settings';
type User = { id: number; name: string; email: string; role: Role; address: string; joined: string };
type StoreRecord = { id: number; name: string; address: string; rating: number; reviews: number; owner: string; yourRating?: number };

const initialUsers: User[] = [
  { id: 1, name: 'Olivia Bennett', email: 'olivia@northstar.com', role: 'user', address: '14 Cedar Lane, Austin', joined: 'Aug 24, 2024' },
  { id: 2, name: 'Marcus Thompson', email: 'marcus@northstar.com', role: 'owner', address: '81 Market Street, Austin', joined: 'Aug 19, 2024' },
  { id: 3, name: 'Sofia Rodriguez', email: 'sofia@northstar.com', role: 'user', address: '7 Rosewood Drive, Austin', joined: 'Aug 17, 2024' },
  { id: 4, name: 'James Wilson', email: 'james@northstar.com', role: 'admin', address: '500 Congress Ave, Austin', joined: 'Aug 12, 2024' },
  { id: 5, name: 'Ava Patel', email: 'ava@northstar.com', role: 'user', address: '23 Willow Street, Austin', joined: 'Aug 08, 2024' },
];
const initialStores: StoreRecord[] = [
  { id: 1, name: 'The Green Table', address: '81 Market Street, Austin, TX', rating: 4.8, reviews: 128, owner: 'Marcus Thompson', yourRating: 5 },
  { id: 2, name: 'Juniper & Co.', address: '204 West 5th Street, Austin, TX', rating: 4.6, reviews: 86, owner: 'Elena Carter', yourRating: 4 },
  { id: 3, name: 'Riverside Roasters', address: '17 Rainey Street, Austin, TX', rating: 4.3, reviews: 64, owner: 'David Kim' },
  { id: 4, name: 'Harvest House', address: '312 South Lamar Blvd, Austin, TX', rating: 4.1, reviews: 42, owner: 'Amelia Stone', yourRating: 4 },
  { id: 5, name: 'Little Owl Bakery', address: '401 East Cesar Chavez, Austin, TX', rating: 3.9, reviews: 31, owner: 'Noah Williams' },
];

const roleLabel = (role: Role) => role === 'admin' ? 'System Admin' : role === 'owner' ? 'Store Owner' : 'Normal User';
const initials = (name: string) => name.split(' ').map((word) => word[0]).join('').slice(0, 2);

function App() {
  const [loggedIn, setLoggedIn] = useState(true);
  const [role, setRole] = useState<Role>('admin');
  const [view, setView] = useState<View>('overview');
  const [users, setUsers] = useState(initialUsers);
  const [stores, setStores] = useState(initialStores);
  const [search, setSearch] = useState('');
  const [mobileOpen, setMobileOpen] = useState(false);
  const [showModal, setShowModal] = useState<'user' | 'store' | null>(null);
  const [toast, setToast] = useState('');

  const title = view === 'overview' ? 'Overview' : view === 'settings' ? 'Account settings' : view === 'stores' ? 'Stores' : view === 'users' ? 'Users' : 'Rating activity';
  const activeUser = users[0];
  const filteredStores = useMemo(() => stores.filter((store) => `${store.name} ${store.address}`.toLowerCase().includes(search.toLowerCase())), [stores, search]);
  const filteredUsers = useMemo(() => users.filter((user) => `${user.name} ${user.email} ${user.role} ${user.address}`.toLowerCase().includes(search.toLowerCase())), [users, search]);

  function notify(message: string) {
    setToast(message);
    window.setTimeout(() => setToast(''), 2600);
  }
  function navigate(next: View) {
    setView(next); setSearch(''); setMobileOpen(false);
  }
  function changeRole(next: Role) {
    setRole(next); setView('overview'); setSearch(''); notify(`Switched to ${roleLabel(next)} preview`);
  }
  function rateStore(id: number, rating: number) {
    setStores((current) => current.map((store) => store.id === id ? { ...store, yourRating: rating, rating: Number(((store.rating * store.reviews + rating) / (store.reviews + 1)).toFixed(1)), reviews: store.reviews + (store.yourRating ? 0 : 1) } : store));
    notify('Your rating was saved');
  }

  if (!loggedIn) return <LoginScreen onLogin={(nextRole) => { setRole(nextRole); setLoggedIn(true); }} />;

  const navItems = ([ 
    { label: 'Overview', icon: LayoutDashboard, view: 'overview' as View, roles: ['admin', 'user', 'owner'] as Role[] },
    { label: 'Stores', icon: Store, view: 'stores' as View, roles: ['admin', 'user'] as Role[] },
    { label: 'Users', icon: Users, view: 'users' as View, roles: ['admin'] as Role[] },
    { label: 'Rating activity', icon: ClipboardList, view: 'ratings' as View, roles: ['owner'] as Role[] },
    { label: 'Account settings', icon: KeyRound, view: 'settings' as View, roles: ['user', 'owner'] as Role[] },
  ] as const).filter((item) => item.roles.includes(role));

  return (
    <div className="app-shell">
      <aside className={`sidebar ${mobileOpen ? 'is-open' : ''}`}>
        <div className="brand"><div className="brand-mark"><Star size={18} fill="currentColor" /></div><span>Northstar</span></div>
        <div className="workspace-label">Workspace</div>
        <nav>{navItems.map(({ label, icon: Icon, view: itemView }) => <button key={itemView} className={view === itemView ? 'nav-item active' : 'nav-item'} onClick={() => navigate(itemView)}><Icon size={18} /><span>{label}</span>{itemView === 'ratings' && <span className="nav-count">12</span>}</button>)}</nav>
        <div className="sidebar-bottom"><div className="help-card"><div className="help-icon"><ShieldCheck size={17} /></div><strong>Rate with confidence</strong><p>Every voice helps great businesses grow.</p></div><button className="account-chip" onClick={() => navigate('settings')}><span className="avatar small">{initials(activeUser.name)}</span><span className="account-text"><b>{activeUser.name}</b><small>{roleLabel(role)}</small></span><ChevronDown size={15} /></button></div>
      </aside>
      {mobileOpen && <button className="mobile-overlay" aria-label="Close menu" onClick={() => setMobileOpen(false)} />}
      <main className="main-content">
        <header className="topbar"><button className="mobile-menu" onClick={() => setMobileOpen(true)}><Menu size={21} /></button><div className="breadcrumbs"><span>Northstar</span><span>/</span><b>{title}</b></div><div className="top-actions"><div className="role-switch"><span className="role-dot" /><select value={role} onChange={(event) => changeRole(event.target.value as Role)} aria-label="Preview role"><option value="admin">Admin view</option><option value="user">User view</option><option value="owner">Owner view</option></select></div><button className="icon-button" aria-label="Profile"><CircleUserRound size={20} /></button><button className="logout-button" onClick={() => setLoggedIn(false)}><LogOut size={17} /><span>Log out</span></button></div></header>
        <div className="page-content">
          {view === 'overview' && <Overview role={role} stores={stores} users={users} navigate={navigate} onRate={rateStore} />}
          {view === 'stores' && <StoresView role={role} stores={filteredStores} search={search} setSearch={setSearch} onRate={rateStore} />}
          {view === 'users' && <UsersView users={filteredUsers} search={search} setSearch={setSearch} onAdd={() => setShowModal('user')} />}
          {view === 'ratings' && <RatingsView stores={stores} />}
          {view === 'settings' && <SettingsView user={activeUser} onSave={() => notify('Password updated successfully')} />}
        </div>
      </main>
      {showModal && <Modal type={showModal} onClose={() => setShowModal(null)} onSave={(value) => { if (showModal === 'user') setUsers((current) => [...current, { id: current.length + 1, name: value.name, email: value.email, role: value.role as Role, address: value.address, joined: 'Just now' }]); else setStores((current) => [...current, { id: current.length + 1, name: value.name, address: value.address, rating: 0, reviews: 0, owner: 'Unassigned' }]); setShowModal(null); notify(`${showModal === 'user' ? 'User' : 'Store'} added successfully`); }} />}
      {toast && <div className="toast"><span className="toast-check">✓</span>{toast}</div>}
    </div>
  );
}

function LoginScreen({ onLogin }: { onLogin: (role: Role) => void }) {
  const [isSignup, setIsSignup] = useState(false);
  const [selectedRole, setSelectedRole] = useState<Role>('admin');
  return <div className="auth-shell"><div className="auth-art"><div className="auth-brand"><div className="brand-mark"><Star size={18} fill="currentColor" /></div>Northstar</div><div className="art-copy"><div className="quote-mark">“</div><h1>Make every experience count.</h1><p>A trusted community where honest feedback helps local businesses shine.</p><div className="art-stats"><div><b>4.8<span>/5</span></b><small>Average rating</small></div><div><b>2,840<span>+</span></b><small>Active members</small></div></div></div><div className="art-shape shape-one" /><div className="art-shape shape-two" /></div><div className="auth-panel"><div className="auth-panel-inner"><div className="mobile-auth-brand"><div className="brand-mark"><Star size={18} fill="currentColor" /></div>Northstar</div><div className="eyebrow">Welcome back</div><h2>{isSignup ? 'Create your account' : 'Sign in to Northstar'}</h2><p className="auth-subtitle">{isSignup ? 'Join a community of thoughtful reviewers.' : 'Your trusted space for authentic feedback.'}</p>{isSignup && <label>Full name<input placeholder="Enter your full name" /></label>}<label>Email address<input type="email" placeholder="you@example.com" defaultValue="admin@northstar.com" /></label><label>Password<div className="input-with-icon"><input type="password" placeholder="Enter your password" defaultValue="Password1!" /><KeyRound size={16} /></div></label>{isSignup && <label>Account type<select value={selectedRole} onChange={(event) => setSelectedRole(event.target.value as Role)}><option value="user">Normal user</option><option value="owner">Store owner</option></select></label>} {!isSignup && <div className="form-row"><label className="check"><input type="checkbox" defaultChecked /> Remember me</label><button className="text-button">Forgot password?</button></div>}<button className="primary-button full" onClick={() => onLogin(isSignup ? selectedRole : selectedRole)}>Continue <span>→</span></button><div className="demo-hint"><span className="hint-dot" />Demo mode · Choose a role below</div><div className="role-pills">{(['admin', 'user', 'owner'] as Role[]).map((item) => <button className={selectedRole === item ? 'selected' : ''} key={item} onClick={() => setSelectedRole(item)}>{roleLabel(item)}</button>)}</div><p className="switch-auth">{isSignup ? 'Already have an account?' : 'New to Northstar?'} <button onClick={() => setIsSignup(!isSignup)}>{isSignup ? 'Sign in' : 'Create an account'}</button></p></div></div></div>;
}

function Overview({ role, stores, users, navigate, onRate }: { role: Role; stores: StoreRecord[]; users: User[]; navigate: (view: View) => void; onRate: (id: number, rating: number) => void }) {
  if (role === 'user') return <><PageHeading eyebrow="Your activity" title="Good morning, Olivia" description="Discover local favorites and share what you think." /><div className="stat-grid three"><StatCard label="Your ratings" value="8" note="2 this month" icon={Star} tone="gold" /><StatCard label="Average you gave" value="4.6" note="Across all stores" icon={BarChart3} tone="blue" /><StatCard label="Stores explored" value="24" note="Keep discovering" icon={Store} tone="green" /></div><section className="section-block"><SectionTitle title="Places waiting for your take" action="View all stores" onAction={() => navigate('stores')} /><div className="store-grid">{stores.slice(0, 3).map((store) => <StoreCard key={store.id} store={store} onRate={onRate} />)}</div></section></>;
  if (role === 'owner') { const myStore = stores[0]; return <><PageHeading eyebrow="Store overview" title="Good morning, Marcus" description="Here’s how The Green Table is performing this month." /><div className="stat-grid three"><StatCard label="Average rating" value={myStore.rating.toFixed(1)} note="+0.3 from last month" icon={Star} tone="gold" /><StatCard label="Total ratings" value={String(myStore.reviews)} note="12 new this month" icon={ClipboardList} tone="blue" /><StatCard label="Store rank" value="#4" note="In Austin · Top 10%" icon={BarChart3} tone="green" /></div><section className="section-block"><SectionTitle title="The Green Table" action="View all ratings" onAction={() => navigate('ratings')} /><div className="owner-panel"><div className="rating-hero"><div className="big-rating">{myStore.rating.toFixed(1)}</div><div><Stars rating={myStore.rating} /><p>Based on {myStore.reviews} ratings</p></div></div><div className="rating-bars">{[5, 4, 3, 2, 1].map((item, index) => <div className="rating-bar-row" key={item}><span>{item}</span><Star size={13} fill="currentColor" /><div className="bar-track"><div className={`bar-fill b${index}`} style={{ width: `${[82, 12, 4, 1, 1][index]}%` }} /></div><small>{[105, 15, 5, 2, 1][index]}</small></div>)}</div></div></section></> }
  return <><PageHeading eyebrow="Tuesday, August 27, 2024" title="Good morning, James" description="Here’s what’s happening across your platform today." action="Add new store" onAction={() => navigate('stores')} /><div className="stat-grid"><StatCard label="Total users" value="1,284" note="12.5% vs last month" icon={Users} tone="blue" trend="up" /><StatCard label="Total stores" value="248" note="8.2% vs last month" icon={Store} tone="green" trend="up" /><StatCard label="Ratings submitted" value="6,492" note="18.4% vs last month" icon={Star} tone="gold" trend="up" /><StatCard label="Avg. platform rating" value="4.6" note="Across all stores" icon={BarChart3} tone="orange" /></div><div className="overview-columns"><section className="section-block recent-block"><SectionTitle title="Recent activity" action="View all" onAction={() => navigate('ratings')} /><div className="activity-list">{users.slice(0, 4).map((user, index) => <div className="activity-item" key={user.id}><div className={`activity-icon activity-${index}`}><Star size={16} fill="currentColor" /></div><div><p><b>{user.name}</b> rated <b>{stores[index % stores.length].name}</b></p><small>{index + 1} hour{index ? 's' : ''} ago</small></div><div className="activity-rating"><Stars rating={index === 0 ? 5 : index === 1 ? 4 : 5} /></div></div>)}</div></section><section className="section-block quick-block"><SectionTitle title="Quick actions" /><button className="quick-action" onClick={() => navigate('users')}><div className="quick-icon blue"><UserRound size={18} /></div><span><b>Add a new user</b><small>Invite someone to the platform</small></span><span className="quick-arrow">→</span></button><button className="quick-action" onClick={() => navigate('stores')}><div className="quick-icon green"><Building2 size={18} /></div><span><b>Add a new store</b><small>Grow your store directory</small></span><span className="quick-arrow">→</span></button></section></div></>;
}

function PageHeading({ eyebrow, title, description, action, onAction }: { eyebrow: string; title: string; description: string; action?: string; onAction?: () => void }) { return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{action && <button className="primary-button" onClick={onAction}><Plus size={17} />{action}</button>}</div> }
function SectionTitle({ title, action, onAction }: { title: string; action?: string; onAction?: () => void }) { return <div className="section-title"><h3>{title}</h3>{action && <button className="link-button" onClick={onAction}>{action} <span>→</span></button>}</div> }
function StatCard({ label, value, note, icon: Icon, tone, trend }: { label: string; value: string; note: string; icon: typeof Users; tone: string; trend?: string }) { return <div className="stat-card"><div className={`stat-icon ${tone}`}><Icon size={19} /></div><div className="stat-label">{label}</div><div className="stat-value">{value}</div><div className={`stat-note ${trend ? 'positive' : ''}`}>{trend && '↗ '}{note}</div></div> }
function Stars({ rating }: { rating: number }) { return <span className="stars">{[1, 2, 3, 4, 5].map((item) => <Star key={item} size={14} fill={item <= Math.round(rating) ? 'currentColor' : 'none'} />)}</span> }
function StoreCard({ store, onRate }: { store: StoreRecord; onRate: (id: number, rating: number) => void }) { return <div className="store-card"><div className="store-card-top"><div className="store-symbol"><Store size={18} /></div><span className="more">•••</span></div><h4>{store.name}</h4><p className="store-address">{store.address}</p><div className="store-rating"><Stars rating={store.rating} /><b>{store.rating.toFixed(1)}</b><span>({store.reviews})</span></div><div className="your-rating"><span>Your rating</span><div className="rate-stars">{[1, 2, 3, 4, 5].map((item) => <button key={item} className={item <= (store.yourRating || 0) ? 'filled' : ''} onClick={() => onRate(store.id, item)} aria-label={`Rate ${item}`}><Star size={18} fill="currentColor" /></button>)}</div></div></div> }

function StoresView({ role, stores, search, setSearch, onRate }: { role: Role; stores: StoreRecord[]; search: string; setSearch: (value: string) => void; onRate: (id: number, rating: number) => void }) { return <><PageHeading eyebrow="Directory" title="Stores" description={role === 'user' ? 'Find a new favorite and share your experience.' : 'Manage every store on the Northstar platform.'} action={role === 'admin' ? 'Add store' : undefined} /><div className="toolbar"><div className="search-box"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by name or address" /></div><button className="filter-button">All ratings <ChevronDown size={15} /></button><button className="sort-button"><ArrowDownAZ size={16} /> Sort by</button></div>{stores.length ? <div className="store-grid full-grid">{stores.map((store) => <StoreCard key={store.id} store={store} onRate={onRate} />)}</div> : <EmptyState text="No stores match that search." />}</> }
function UsersView({ users, search, setSearch, onAdd }: { users: User[]; search: string; setSearch: (value: string) => void; onAdd: () => void }) { return <><PageHeading eyebrow="Directory management" title="Users" description="Manage members, owners, and administrators." action="Add user" onAction={onAdd} /><div className="toolbar"><div className="search-box wide"><Search size={17} /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by name, email, or address" /></div><button className="filter-button">All roles <ChevronDown size={15} /></button><button className="sort-button"><ArrowUpAZ size={16} /> Name</button></div><div className="table-card"><table><thead><tr><th>Name</th><th>Role</th><th>Address</th><th>Joined</th><th /></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td><div className="person-cell"><span className="avatar">{initials(user.name)}</span><span><b>{user.name}</b><small>{user.email}</small></span></div></td><td><span className={`role-badge ${user.role}`}>{roleLabel(user.role)}</span></td><td>{user.address}</td><td>{user.joined}</td><td><button className="row-menu">•••</button></td></tr>)}</tbody></table><div className="pagination"><span>Showing 1–{users.length} of 1,284 users</span><div><button>‹</button><button className="current">1</button><button>2</button><button>3</button><button>›</button></div></div></div></> }
function RatingsView({ stores }: { stores: StoreRecord[] }) { return <><PageHeading eyebrow="The Green Table" title="Rating activity" description="See who’s sharing feedback about your store." /><div className="rating-summary"><div><span className="summary-label">Overall rating</span><strong>{stores[0].rating.toFixed(1)}</strong><Stars rating={stores[0].rating} /></div><div><span className="summary-label">Total ratings</span><strong>{stores[0].reviews}</strong><small>+12 this month</small></div><div><span className="summary-label">Response rate</span><strong>96%</strong><small>Excellent</small></div></div><div className="table-card"><div className="table-heading"><h3>Recent ratings</h3><div className="search-box compact"><Search size={16} /><input placeholder="Search reviewers" /></div></div><table><thead><tr><th>Reviewer</th><th>Rating</th><th>Review date</th><th>Comment</th></tr></thead><tbody>{['Olivia Bennett', 'Sofia Rodriguez', 'Ava Patel', 'Liam Anderson'].map((name, index) => <tr key={name}><td><div className="person-cell"><span className="avatar">{initials(name)}</span><span><b>{name}</b><small>{name.split(' ')[0].toLowerCase()}@northstar.com</small></span></div></td><td><span className="rating-number"><Star size={14} fill="currentColor" />{[5, 5, 4, 5][index]}.0</span></td><td>{['Aug 27, 2024', 'Aug 26, 2024', 'Aug 25, 2024', 'Aug 23, 2024'][index]}</td><td className="muted-cell">{['Wonderful atmosphere and kind staff.', 'My favorite spot in the city.', 'Great coffee, will be back.', 'Always a lovely experience.'][index]}</td></tr>)}</tbody></table></div></> }
function SettingsView({ user, onSave }: { user: User; onSave: () => void }) { return <><PageHeading eyebrow="Your account" title="Account settings" description="Keep your account details and password up to date." /><div className="settings-layout"><div className="settings-card"><div className="settings-card-title"><div className="avatar large">{initials(user.name)}</div><div><h3>{user.name}</h3><p>{user.email}</p></div></div><div className="form-grid"><label>Full name<input defaultValue={user.name} /></label><label>Email address<input defaultValue={user.email} /></label><label className="span-2">Address<input defaultValue={user.address} /></label></div><button className="primary-button" onClick={onSave}>Save changes</button></div><div className="settings-card"><div className="eyebrow">Security</div><h3>Change password</h3><p className="card-description">Use a unique password with at least 8 characters.</p><label>Current password<input type="password" placeholder="Enter current password" /></label><label>New password<input type="password" placeholder="Enter new password" /></label><label>Confirm new password<input type="password" placeholder="Repeat new password" /></label><button className="secondary-button" onClick={onSave}>Update password</button></div></div></> }
function EmptyState({ text }: { text: string }) { return <div className="empty-state"><Search size={24} /><p>{text}</p></div> }
function Modal({ type, onClose, onSave }: { type: 'user' | 'store'; onClose: () => void; onSave: (value: { name: string; email: string; role: string; address: string }) => void }) { const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [address, setAddress] = useState(''); const [role, setRole] = useState('user'); return <div className="modal-backdrop"><div className="modal"><div className="modal-header"><div><div className="eyebrow">New record</div><h2>{type === 'user' ? 'Add a new user' : 'Add a new store'}</h2></div><button onClick={onClose}><X size={19} /></button></div><label>{type === 'user' ? 'Full name' : 'Store name'}<input value={name} onChange={(event) => setName(event.target.value)} placeholder={type === 'user' ? 'Enter full name' : 'Enter store name'} /></label>{type === 'user' && <><label>Email address<input value={email} onChange={(event) => setEmail(event.target.value)} placeholder="name@example.com" /></label><label>Role<select value={role} onChange={(event) => setRole(event.target.value)}><option value="user">Normal user</option><option value="owner">Store owner</option><option value="admin">System admin</option></select></label></>}<label>Address<input value={address} onChange={(event) => setAddress(event.target.value)} placeholder="Enter address" /></label><div className="modal-actions"><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" onClick={() => onSave({ name: name || 'New record', email: email || 'new@northstar.com', role, address: address || 'Austin, TX' })}>Add {type}</button></div></div></div> }
export default App;
